env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - echo "🚀"

builds:
  - binary: go-bench-away
    ldflags: -s -w -X github.com/mprimi/go-bench-away/v1/core.Version={{ .Version }} -X github.com/mprimi/go-bench-away/v1/core.SHA={{ .ShortCommit }} -X github.com/mprimi/go-bench-away/v1/core.BuildDate={{ .Date }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - builds:
      - go-bench-away
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^assets:"
      - "^scripts:"
